### PR TITLE
Improved codebase and updated embed description character limit

### PR DESCRIPTION
**Pull request by X1nto**
Here are the changes so far:
- Refactored code, used JS destructive types ([more info on that](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)), removed useless else statements (nothing much changed with the code style, just cleaned it up)
- Removed the `replace(regex)` function from lyrics, as it does absolutely nothing. As far as I understood, you wanted to remove the space between verses (which kind of ruins the readability of lyrics), but if you still want to do that, please consider using this regex instead `/(?:(\n|\r)+)/g`
- Removed the useless DuckDuckGo redirect link for the footer icon and replaced it with a direct image link
- Updated embed description limit to 2048 characters since it's the actual maximum discord supports

Overall the command might be a tiny little bit faster (even tho it won't be noticeable with a naked eye 😄)

The code contains additional comments so it's easier to understand this refactored version. ~~Since this PR doesn't bring any new features, there's no need to hurry to merge it.~~ If you have any questions about the new code, feel free to ask as I'm happy to explain.

Credits to @Vendicated for helping me with the stuff

### CODE REVIEW

**Comment by davidcralph** [comment]
Thank you for the pull request! Apologies for responding so late, here's a few comments:

> Removed the useless DuckDuckGo redirect link for the footer icon and replaced it with a direct image link

This was intentional, because from my checking it Discord doesn't appear to proxy the local embed images. I may be wrong however. I wanted to limit requests outside of ``powercord.dev`` domains wherever possible.

> Removed the replace(regex) function from lyrics, as it does absolutely nothing. As far as I understood, you wanted to remove the space between verses (which kind of ruins the readability of lyrics), but if you still want to do that, please consider using this regex instead /(?:(\n|\r)+)/g

I wrote this a long time ago 😄 so I'm not even sure why I put it there in the first place. I'm sure it'll be fine.

The rest of the pull request LGTM, so I'll merge this once we've reached a decision regarding the top comment 👍

**Comment by X1nto** [comment]
> > Removed the useless DuckDuckGo redirect link for the footer icon and replaced it with a direct image link
> 
> This was intentional, because from my checking it Discord doesn't appear to proxy the local embed images. I may be wrong however. I wanted to limit requests outside of ``powercord.dev`` domains wherever possible.

From my personal tests, footer icon appeared properly, but if there was an intention to use the redirect in the first place, I guess it's better to revert this change to make sure nothing gets screwed up. Will push changes as soon as I get hands on my PC. Thanks for the feedback 👍

**Comment by X1nto** [comment]
Done.

**Comment by davidcralph** [comment]
🎉

**Pull request merged**
